token:
  lifespan: 300

l10n:
  defaultLocale: 'ru'

dataDisplay:
  quickSearchMaxItems: 15
  numberFractionalLength: 2
  listItemsOnPage: 50

dataEntry:
  accountNumberLength: 20

sections:
  company: /my-company
  requests: /my-requests
  customerRequests: /customer-requests
  heads: /company-heads
  bankDetails: /bank-details
  documents: /documents
  questionnaire: /questionnaire

roles:
  pages:
    requests:
      - client
    customerRequests:
      - customer
    all:
      - admin
      - client
      - customer
