token:
  lifespan: 300

l10n:
  defaultLocale: 'ru'

dataDisplay:
  quickSearchMaxItems: 15
  numberFractionalLength: 2

sections:
  company: /my-company
  heads: /company-heads
  bankDetails: /bank-details
  documents: /documents
  requests: /requests

roles:
  pages:
    all:
      - admin
      - operator
