token:
  lifespan: 300

l10n:
  defaultLocale: 'ru'

dataDisplay:
  quickSearchMaxItems: 15
  numberFractionalLength: 2

dataEntry:
  accountNumberLength: 20

sections:
  company: /my-company
  heads: /company-heads
  bankDetails: /bank-details
  documents: /documents
  requests: /my-requests
  toSign: /to-sign

roles:
  pages:
    all:
      - admin
      - operator
