token:
  lifespan: 300

l10n:
  defaultLocale: 'ru'

dataDisplay:
  numberFractionalLength: 2

sections:
  сompany: /my-сompany
  heads: /сompany-heads
  bankDetails: /bank-details
  documents: /documents
  requests: /requests

roles:
  pages:
    all:
      - admin
      - operator
