import { useState, useEffect } from 'react'
import { useTranslation } from 'react-i18next'

import { Typography, Skeleton, Result, Spin, Row, Col, Button } from 'antd'
import { ClockCircleFilled } from '@ant-design/icons'

import Div from 'orient-ui-library/components/Div'
import ErrorResultView from 'orient-ui-library/components/ErrorResultView'
import { OrderDocument } from 'orient-ui-library/library/models/document'
import { FrameWizardStepResponse } from 'orient-ui-library/library/models/wizard'
import { FactoringStatus } from 'orient-ui-library/library/models'

import OrderDocumentsToSignList from 'components/OrderDocumentsToSignList'

import { getFactoringWizardStep } from 'library/api/factoringWizard'

import './FactoringStepBankOffers.style.less'

const { Title } = Typography

export interface FactoringStepBankOffersProps {
  orderId?: number
  companyId?: number
  currentStep: number
  sequenceStepNumber: number
  setCurrentStep: (step: number) => void
  orderStatus: FactoringStatus
}

const FactoringStepBankOffers: React.FC<FactoringStepBankOffersProps> = ({
  orderId,
  companyId,
  currentStep,
  sequenceStepNumber,
  setCurrentStep,
  orderStatus,
}) => {
  const { t } = useTranslation()

  const [ isPrevStepAllowed, _setPrevStepAllowed ] = useState<boolean>(true)

  const [ stepData, setStepData ] = useState<any>() // TODO: ask be to generate models
  const [ stepDataLoading, setStepDataLoading ] = useState<boolean>()
  const [ dataLoaded, setDataLoaded ] = useState<boolean>()

  const [ documentsLoading, setDocumentsLoading ] = useState<boolean>(true)
  const [ documentTypes, setDocumentTypes ] = useState<number[] | null>(null)
  const [ documents, setDocuments ] = useState<OrderDocument[]>([])
  const [ documentTypesGenerated, setDocumentTypesGenerated ] = useState<number[]>()
  const [ documentsGenerated, setDocumentsGenerated ] = useState<OrderDocument[] | null>()

  useEffect(() => {
    loadStepData()
  }, [ currentStep ])

  useEffect(() => {
    if (!stepData) return

    const currentDocuments = stepData?.documents ?? []
    const updatedDocuments: OrderDocument[] = []
    const updatedDocumentsGenerated: OrderDocument[] = []
    const updatedDocumentTypes: number[] = []
    const updatedDocumentTypesGenerated: number[] = []

    currentDocuments
      .forEach((doc: OrderDocument) => {
        if (doc.isGenerated) {
          updatedDocumentTypesGenerated.push(doc.typeId)
          updatedDocumentsGenerated.push(doc)
        } else {
          updatedDocumentTypes.push(doc.typeId)
          updatedDocuments.push(doc)
        }
      })

    setDocuments(updatedDocuments)
    setDocumentTypes(updatedDocumentTypes)
    setDocumentTypesGenerated(updatedDocumentTypesGenerated)
    setDocumentsGenerated(updatedDocumentsGenerated.length ? updatedDocumentsGenerated : null)
    setDocumentsLoading(false)
  }, [ stepData ])

  const loadStepData = async () => {
    if (documentTypes === null) {
      // NOTE: do not show loader every time updates
      setDocumentsLoading(true)
    }
    const result = await getFactoringWizardStep({
      step: sequenceStepNumber,
      companyId: companyId as number,
      orderId,
    })
    if (result.success) {
      setStepData((result.data as FrameWizardStepResponse<any>).data) // TODO: ask be to generate models
      setDataLoaded(true)
    } else {
      setDataLoaded(false)
    }
    setStepDataLoading(false)
  }

  const handlePrevStep = () => {
    if (isPrevStepAllowed) {
      setCurrentStep(sequenceStepNumber - 1)
    }
  }

  const renderPrevStepButton = () => {
    // NOTE: disabled as we can't go back by status model
    return (
      <Button
        size="large"
        type="primary"
        onClick={handlePrevStep}
        disabled={!isPrevStepAllowed}
      >
        {t('common.actions.back.title')}
      </Button>
    )
  }

  const renderActions = () => (
    <Row className="WizardStep__actions">
      <Col>{renderPrevStepButton()}</Col>
      <Col flex={1}></Col>
    </Row>
  )

  const renderDocuments = () => (
    <Spin spinning={documentsLoading}>
      <OrderDocumentsToSignList
        companyId={companyId as number}
        orderId={orderId as number}
        types={documentTypes || []}
        current={documents}
      />
    </Spin>
  )

  const renderGeneratedDocumentsSection = () => (
    <Div className="WizardStep__section">
      <Title level={5}>{t('orderStepDocuments.sectionTitles.autoGeneratedDocs')}</Title>
      {renderGeneratedDocuments()}
    </Div>
  )

  const renderGeneratedDocuments = () => (
    <Spin spinning={documentsLoading}>
      <OrderDocumentsToSignList
        companyId={companyId as number}
        orderId={orderId as number}
        types={documentTypesGenerated as number[]}
        current={documentsGenerated as OrderDocument[]}
      />
    </Spin>
  )

  const renderStepContent = () => (
    <Div className="FactoringStepBankOffers">
      <Div className="FactoringStepBankOffers__title">
        <Title level={4}>{t('orderStepDocuments.title')}</Title>
      </Div>
      <Div className="WizardStep__section">
        <Title level={5}>{t('orderStepDocuments.sectionTitles.mainDocs')}</Title>
        {renderDocuments()}
      </Div>
      {documentsGenerated !== null && renderGeneratedDocumentsSection()}
    </Div>
  )

  if (!stepData && stepDataLoading) {
    return (
      <Skeleton active={true}/>
    )
  }

  if (dataLoaded === false) {
    return (
      <ErrorResultView centered status="warning"/>
    )
  }

  if (orderStatus !== FactoringStatus.FACTOR_CLIENT_SIGN) {
    // TODO: revise l10ns
    return (
      <Result
        icon={<ClockCircleFilled />}
        title={t('orderStepBankOffer.statuses.waitingForBank.title')}
      />
    )
  }

  return (
    <Div className="WizardStep__content">
      {renderStepContent()}
      {renderActions()}
    </Div>
  )
}

export default FactoringStepBankOffers
